kube-prometheus-stack:
  pushgateway:
    enabled: false
  alertmanager:
    ingress:
      enabled: true
      hosts:
        - alertmanager.k3s.zremal.org
    alertmanagerSpec:
      storage:
        volumeClaimTemplate:
          spec:
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 5Gi
  grafana:
    ingress:
      enabled: true
      hosts:
        - grafana.k3s.zremal.org
  prometheus:
    thanosIngress:
      enabled: false
      hosts:
        - thanos-gateway.k3s.zremal.org
    ingress:
      enabled: true
      hosts:
        - prometheus.k3s.zremal.org
    prometheusSpec:
      # serviceMonitorSelector:
      #   matchLabels:
      #     prometheus: monitor
      storageSpec:
        volumeClaimTemplate:
          spec:
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 10Gi